# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ai8 Limited
description: > # this means to ignore newlines until "baseurl:"
  Based on <a href="http://materializecss.com">Materialize.css</a> for jekyll sites
#baseurl: "/matjek"
url: "https://phbs-ai-finance.github.io/"
permalink: /:year/:month/:day/:title
repository: PHBS-AI-Finance/PHBS-AI-Finance.github.io
paginate: 5

# Linkedin Links
linkedin_profile_am: "https://www.linkedin.com/in/alastairmoore/"
linkedin_profile_js: "https://www.linkedin.com/in/jiangbo-shangguan-b1031373/"

# Site Info
home_page: "https://phbs-ai-finance.github.io/"

# Notebook Info
notebook_list:
  - name: "Notebook Week_1"
    link: "https://www.dropbox.com/s/h2r8soqrj8d6hrm/Week_1.ipynb?dl=1"
  - name: "Exercise Week_1"
    link: "https://www.dropbox.com/s/8r4m2hrneity6hz/Week_1_Exercise.ipynb?dl=1"
  - name: "Exercise Solution Week_1"
    link: "https://www.dropbox.com/s/1iqn8djp591m9g8/Week_1_Exercise_Solution.ipynb?dl=1"
  - name: "Notebook Week_2"
    link: "https://www.dropbox.com/s/bvnnslllq56gbcx/Week_2.ipynb?dl=1"
  - name: "Exercise Week_2"
    link: "https://www.dropbox.com/s/f33jedrb8e71f0j/Week_2_Exercise.ipynb?dl=1"
  - name: "Exercise Solution Week_2"
    link: "https://www.dropbox.com/s/scrfl4etz8w8qby/Week_2_Exercise_Solution.ipynb?dl=1"


# Reading info
reading_list:
  - tag: "Week_1"
    content:
      - name: "Artificial Intelligence in Finance Report"
        link: "https://www.turing.ac.uk/sites/default/files/2019-04/artificial_intelligence_in_finance_-_turing_report_1.pdf"
      - name: "A Visual Introduction to Tree"
        link: "http://www.r2d3.us/visual-intro-to-machine-learning-part-1/"

# Slides info
slides_list:
  - name: "Week 1"
    link: "https://www.dropbox.com/s/3efiimp1aivc0o6/Week_1.pdf?dl=1"
  - name: "Week 2"
    link: "https://www.dropbox.com/s/29kso5dnhvozxax/Week_2.pdf?dl=1"

# Quiz Link
quiz_list:
  #- name: "Quiz_test"
  #  link: "https://github.com/PHBS-AI-Finance/Quiz_Test"
#contact_url: "https://goo.gl/tVljbV"
#google_tracking_id: "UA-96359860-1"
#google_site_verification: "UA-96359860-1"
#disqus_shortname: "matjek"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
