# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ai8 Limited
description: > # this means to ignore newlines until "baseurl:"
  Based on <a href="http://materializecss.com">Materialize.css</a> for jekyll sites
#baseurl: "/matjek"
url: "https://phbs-ai-finance.github.io/"
permalink: /:year/:month/:day/:title
repository: PHBS-AI-Finance/PHBS-AI-Finance.github.io
paginate: 5

# Linkedin Links
linkedin_profile_am: "https://www.linkedin.com/in/alastairmoore/"
linkedin_profile_js: "https://www.linkedin.com/in/jiangbo-shangguan-b1031373/"

# Site Info
home_page: "https://phbs-ai-finance.github.io/"

# Notebook Info
notebook_list:
  - name: "Notebook Week_1"
    link: "https://www.dropbox.com/s/h2r8soqrj8d6hrm/Week_1.ipynb?dl=1"
  - name: "Exercise Week_1"
    link: "https://www.dropbox.com/s/8r4m2hrneity6hz/Week_1_Exercise.ipynb?dl=1"
  - name: "Exercise Solution Week_1"
    link: "https://www.dropbox.com/s/1iqn8djp591m9g8/Week_1_Exercise_Solution.ipynb?dl=1"
  - name: "Notebook Week_2"
    link: "https://www.dropbox.com/s/bvnnslllq56gbcx/Week_2.ipynb?dl=1"
  - name: "Exercise Week_2"
    link: "https://www.dropbox.com/s/f33jedrb8e71f0j/Week_2_Exercise.ipynb?dl=1"
  - name: "Exercise Solution Week_2"
    link: "https://www.dropbox.com/s/scrfl4etz8w8qby/Week_2_Exercise_Solution.ipynb?dl=1"
  - name: "Notebook Week_3"
    link: "https://www.dropbox.com/s/226kowfwmi3k8od/Week_3.ipynb?dl=1"
  - name: "Notebook Week_4"
    link: "https://www.dropbox.com/s/9v4dxm2odrmdzr1/Week_4.ipynb?dl=1"
  - name: "Notebook Week_5"
    link: "https://www.dropbox.com/s/yh7x9zduj983vdz/Week_5.ipynb?dl=1"
  - name: "Notebook Week_6"
    link: "https://www.dropbox.com/s/mvcyjuuio5fremj/Week_6.ipynb?dl=1"

# Reading info
reading_list:
  - tag: "Week_1"
    content:
      - name: "Artificial Intelligence in Finance Report"
        link: "https://www.turing.ac.uk/sites/default/files/2019-04/artificial_intelligence_in_finance_-_turing_report_1.pdf"
      - name: "A Visual Introduction to Tree"
        link: "http://www.r2d3.us/visual-intro-to-machine-learning-part-1/"
  - tag: "Example Reports"
    content:
      - name: "Loan Prediction Model"
        link: "https://www.dropbox.com/s/zljy308s2m62jbt/LOAN%20PREDICTION%20MODEL.pdf?dl=1"
      - name: "China and U.S. Stock Prices Prediction based on XGBoost"
        link: "https://www.dropbox.com/s/pis2g7b0wq4wj3v/China%20and%20U.S.%20Stock%20Prices%20Prediction%20based%20on%20XGBoost.pdf?dl=1"
      - name: "A Study of IPO Initial Returns Based on Machine Learning"
        link: "https://www.dropbox.com/s/wc4b5fjbvoqall2/A%20Study%20of%20IPO%20Initial%20Returns%20Based%20on%20Machine%20Learning.pdf?dl=1"

# Slides info
slides_list:
  - name: "Week 1"
    link: "https://www.dropbox.com/s/3efiimp1aivc0o6/Week_1.pdf?dl=1"
  - name: "Week 2"
    link: "https://www.dropbox.com/s/29kso5dnhvozxax/Week_2.pdf?dl=1"
  - name: "Week 3 - A"
    link: "https://www.dropbox.com/s/vt2desjln13hhrq/Week_3.pdf?dl=1"
  - name: "Week 3 - B"
    link: "https://www.dropbox.com/s/3w3yl9zauku5yak/Week_3_B.pdf?dl=1"
  - name: "Week 4"
    link: "https://www.dropbox.com/s/457yf8ry7v0wac2/Week_4.pdf?dl=1"
  - name: "Week 5"
    link: "https://www.dropbox.com/s/jy200spu2n796ll/Week_5.pdf?dl=1"
  - name: "Week 6"
    link: "https://www.dropbox.com/s/jwl75pvsxsry0aa/Week_6.pdf?dl=1"
  - name: "Week 7"
    link: "https://www.dropbox.com/s/w4gio5iulpnrx9y/Week_7.pdf?dl=1"
  - name: "Week 8"
    link: "https://www.dropbox.com/s/rdl8h2sj5stctmw/Week_8.pdf?dl=1"

# Quiz Link
quiz_list:
  - name: "Quiz_1"
    link: "https://www.dropbox.com/s/waqfhk5l8g02rfb/Quiz_1.ipynb?dl=1"
  - name: "Quiz_1 Solution"
    link: "https://www.dropbox.com/s/999g1jndhdzr4cu/Quiz_1_Solution.ipynb?dl=1"
  - name: "Quiz_2"
    link: "https://www.dropbox.com/s/zr2sf4xrxdshnc9/Quiz_2.ipynb?dl=1"
  - name: "Quiz_2 Solution"
    link: "https://www.dropbox.com/s/1jew3xft5ilt6yi/Quiz_2_Solution.ipynb?dl=1"
  - name: "Quiz_3"
    link: "https://www.dropbox.com/s/sp80jbxwpyyss8r/Quiz_3.ipynb?dl=1"
  - name: "Quiz_3 Solution"
    link: "https://www.dropbox.com/s/rggr754er22qlsz/Quiz_3_Solution.ipynb?dl=1"
  - name: "Quiz_4"
    link: "https://www.dropbox.com/s/qgidpvzrifbglrk/Quiz_4.ipynb?dl=1"
  - name: "Quiz_4 Solution"
    link: "https://www.dropbox.com/s/rwwn80f7vhaumgo/Quiz_4_Solution.ipynb?dl=1"

# Recording link
recording_list:
  - name: "Lecture 1"
    link: "https://www.dropbox.com/s/erxxjgvhvrr8p95/Week_1.mp4?dl=0"
  - name: "Lecture 2"
    link: "https://www.dropbox.com/s/jaa9g8bufmfq74e/Week_2.mp4?dl=0"
  - name: "Lecture 3"
    link: "https://www.dropbox.com/s/9wjs9yoh6nskyjy/Week_3.mp4?dl=0"
  - name: "Lecture 4"
    link: "https://www.dropbox.com/s/yga1fudgkf311jp/Week_4.mp4?dl=0"
#contact_url: "https://goo.gl/tVljbV"
#google_tracking_id: "UA-96359860-1"
#google_site_verification: "UA-96359860-1"
#disqus_shortname: "matjek"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
