# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Demonstrable Labs
description: > # this means to ignore newlines until "baseurl:"
  Based on <a href="http://materializecss.com">Materialize.css</a> for jekyll sites
#baseurl: "/matjek"
url: "https://phbs-ai-finance.github.io/"
permalink: /:year/:month/:day/:title
repository: PHBS-AI-Finance/PHBS-AI-Finance.github.io
paginate: 5

# Linkedin Links
linkedin_profile_am: "https://www.linkedin.com/in/alastairmoore/"
linkedin_profile_js: "https://www.linkedin.com/in/jiangbo-shangguan-b1031373/"

# Site Info
home_page: "https://phbs-ai-finance.github.io/"

# Notebook Info
notebook_list:
  - name: "Notebook Week_1"
    link: "https://github.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/blob/master/Week_1.zip?raw=true"
  - name: "Exercise Week_1"
    link: "https://raw.githubusercontent.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/master/Week_1_Exercise.ipynb"
  - name: "AVerySimpleTree"
    link: "https://raw.githubusercontent.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/master/AVerySimpleTree.ipynb"
  - name: "Exercise Solution Week_1"
    link: "https://raw.githubusercontent.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/master/Week_1_Exercise_Solution.ipynb"
  - name: "AVerySimpleTree Solution"
    link: "https://raw.githubusercontent.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/master/AVerySimpleTree_Solution.ipynb"
  - name: "Notebook Week_2"
    link: "https://github.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/blob/master/Week_2.zip?raw=true"
  - name: "Exercise Week_2"
    link: "https://raw.githubusercontent.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/master/Week_2_Exercise.ipynb"
  - name: "ASimpleTree"
    link: "https://github.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/blob/master/ASimpleTree.zip?raw=true"
  - name: "ASimpleTree Solution"
    link: "https://github.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/blob/master/ASimpleTree_Solution.zip?raw=true"
  - name: "Exercise Solution Week_2"
    link: "https://raw.githubusercontent.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/master/Week_2_Exercise_Solution.ipynb"
  - name: "Notebook Week_3"
    link: "https://github.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/blob/master/Week_3.zip?raw=true"
  - name: "Notebook Week_4"
    link: "https://github.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/blob/master/Week_4.zip?raw=true"
  - name: "Numpy Exercise"
    link: "https://raw.githubusercontent.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/master/Numpy_Exercise.ipynb"
  - name: "Numpy Exercise Solution"
    link: "https://raw.githubusercontent.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/master/Numpy_Exercise_Solution.ipynb"
  - name: "Notebook Week_5"
    link: "https://github.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/blob/master/Week_5.ipynb?raw=true"
  - name: "Pandas Exercise"
    link: "https://raw.githubusercontent.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/master/Pandas_Exercise.ipynb"
  - name: "Pandas Exercise Solution"
    link: "https://raw.githubusercontent.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/master/Pandas_Exercise_Solution.ipynb"


# Reading info
reading_list:
  - tag: "Week_1"
    content:
      - name: "Artificial Intelligence in Finance Report"
        link: "https://www.turing.ac.uk/sites/default/files/2019-04/artificial_intelligence_in_finance_-_turing_report_1.pdf"
      - name: "A Visual Introduction to Tree"
        link: "http://www.r2d3.us/visual-intro-to-machine-learning-part-1/"

# Slides info
slides_list:
  - name: "Week 1"
    link: "https://github.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/blob/master/Week_1.pdf?raw=true"
  - name: "Week 2"
    link: "https://github.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/blob/master/Week_2.pdf?raw=true"
  - name: "Week 3"
    link: "https://www.dropbox.com/s/hkhklhvth3887j9/Week_3.pdf?dl=0"
  - name: "Week 4"
    link: "https://www.dropbox.com/s/f1ifj3tl1cwk8rr/Week_4.pdf?dl=0"
  - name: "Week 5 (with annotations)"
    link: "https://www.dropbox.com/s/1eas2gors0j046h/Week_5.pdf?dl=0"
  - name: "Google Colab Tutorial"
    link: "https://github.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/blob/master/Google_Colab_Tutorial.pdf?raw=true"
  - name: "Week 6 (with annotations)"
    link: "https://www.dropbox.com/s/6j8ey96g2pa6vx2/Week_6%20annotated.pdf?dl=0"

# Quiz Link
quiz_list:
  - name: "Quiz_test"
    link: "https://github.com/PHBS-AI-Finance/Quiz_Test"
  - name: "Quiz_1"
    link: "https://github.com/PHBS-AI-Finance/Quiz_1"
  - name: "Quiz_1 Solutions"
    link: "https://raw.githubusercontent.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/master/Quiz_1_Solution.ipynb"
  - name: "Quiz_2"
    link: "https://github.com/PHBS-AI-Finance/Quiz_2"
  - name: "Quiz_2 Solutions"
    link: "https://raw.githubusercontent.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/master/Quiz_2_Solution.ipynb"
  - name: "Quiz_3"
    link: "https://github.com/PHBS-AI-Finance/Quiz_3"
  - name: "Quiz_3 Solutions"
    link: "https://raw.githubusercontent.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/master/Quiz_3_Solution.ipynb"
  - name: "Quiz_4"
    link: "https://github.com/PHBS-AI-Finance/Quiz_4"
  - name: "Quiz_4 Solutions"
    link: "https://raw.githubusercontent.com/PHBS-AI-Finance/AI-Analytics-PHBS-UK/master/Quiz_4_Solution.ipynb"
#contact_url: "https://goo.gl/tVljbV"
#google_tracking_id: "UA-96359860-1"
#google_site_verification: "UA-96359860-1"
#disqus_shortname: "matjek"

# Build settings
markdown: kramdown
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  style: compressed
future: true
